import {
  Candy,
  Cherry,
  Clover,
  Rocket,
  Disc3,
  Spade,
  Gem,
  PiggyBank,
  Donut,
  Flame,
  Dice5,
  Crown,
  Gift,
  Coins,
  Clock,
  Sparkles,
  FerrisWheel,
  Circle,
  type LucideIcon,
} from "lucide-react";

export const iconMap = {
  candy: Candy,
  cherry: Cherry,
  clover: Clover,
  rocket: Rocket,
  disc: Disc3,
  spade: Spade,
  gem: Gem,
  piggy: PiggyBank,
  donut: Donut,
  flame: Flame,
  dice: Dice5,
  crown: Crown,
  gift: Gift,
  coins: Coins,
  clock: Clock,
  sparkles: Sparkles,
  wheel: FerrisWheel,
  circle: Circle,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof iconMap;
